openimis/openimis-be-product_py

product/models.py
product/test_helpers.py

Add some constants, a link from Product to Location and the test helpers that were extracted from the claim module

OMT-51 Product -> Location + dispatch test helpers

---

.github/workflows/python-publish.yml
.gitignore
locale/en/LC_MESSAGES/django.po
product/admin.py
product/models.py
product/schema.py
product/test_helpers.py
product/views.py
setup.py

This PR is only intended to show the LGTM fix on the develop branch.
DO NOT MERGE

develop to main for LGTM

---

product/gql_mutations.py

Ticket: https://openimis.atlassian.net/browse/OP-909
Changes:
- Added checks for children O,R,E values.
- Added checks for upper bound (100% percent)
- Service/Item separate message added.

OP-909: Checks for 100 percent and children O,R,E added.

---

product/schema.py

https://openimis.atlassian.net/browse/OP-1012

OP-1012: modular IMIS: searching for insurance product of a pecific region should give all product valid for given region

---

product/schema.py

https://openimis.atlassian.net/browse/OP-1047

OP-1047: modular IMIS: objects not belonging to the territorial range of a user displayed and even can be manipulated

---

product/schema.py
product/services.py

https://openimis.atlassian.net/browse/OP-1059

OP-1059: modular IMIS: not able to modify insurance products at all

---

product/apps.py
product/schema.py

https://openimis.atlassian.net/browse/OP-1050
This PR is also connected with this pull request in frontend module: https://github.com/openimis/openimis-fe-product_js/pull/19

OP-1050: create query that returns default values for limits in product's items and services

---

product/apps.py
product/schema.py

https://openimis.atlassian.net/browse/OP-987
This PR allows frontend part (link below) to get default values for items and services.
https://github.com/openimis/openimis-fe-product_js/pull/21

OP-987: provide default values for items and services

---

product/gql_mutations.py
product/schema.py
product/services.py

https://openimis.atlassian.net/browse/OTC-881
Changes:
- Added query for checking of the uniqueness of the product code
- Backend now blocks saving if code is not unique
- Query checks for user permission before responding

OTC-881: Product code uniqueness query and check.

---

product/gql_mutations.py

https://openimis.atlassian.net/browse/OTC-880

OTC-880: Product module doesn't update the validityFrom and validtiyTo dates correctly when modifying a product

---

product/gql_mutations.py
product/schema.py

Ticket: https://openimis.atlassian.net/browse/OTC-856
Changes:
- New mutation for duplication of product.

OTC-856: Duplicate product mutation

---

product/gql_mutations.py

https://openimis.atlassian.net/browse/OP-1333
This PR changes the validation of O R E limits in service and item in product to not validate to upper limit when FIXED price.

OP-1333: change validation of item/services O R E limits

---

product/gql_mutations.py
product/schema.py

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

product/gql_mutations.py

https://openimis.atlassian.net/browse/OP-1399
This PR fixes error that occurred when validating product item.

OP-1399: get value from first index of tuple

---

product/gql_mutations.py

https://openimis.atlassian.net/browse/OP-1443
This PR will not allow to edit product if is a historical instance.

OP-1443: don't allow to edit historical data

---

product/gql_mutations.py
product/schema.py
product/services.py

https://openimis.atlassian.net/browse/OP-1450
This PR will acknowledge changes in items and services when editing product. It will also pass items and services to frontend when displaying historical data.

OP-1450: include items/services in historical products

---

product/schema.py

[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)

CM-188 Adjusted backend for social protection

---

product/apps.py

https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.

OP-1518: load config

---

product/schema.py

https://openimis.atlassian.net/browse/ONI-180
Changes:
- Missing import added

ONI-180: Add missing LocationManager import.

---

product/migrations/0001_initial.py

Sometime DB migration will fail if production migration is done before location migration

fix location not loaded error

---

product/migrations/0001_initial.py

MERGING develop into release/24.04

MERGING develop into release/24.04
